/**
 * testLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { string } from '../schema';
import { BaseController } from './baseController';

export class ApiController extends BaseController {
  /**
   * some desc
   *
   * @param testparam some desc
   * @return Response from the API call
   */
  async test(
    testparam: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/get');
    const mapped = req.prepareArgs({ testparam: [testparam, string()] });
    req.query('testparam', mapped.testparam);
    return req.call(requestOptions);
  }

  /**
   * some desc
   *
   * @param test some desc
   * @return Response from the API call
   */
  async testEndpoint2(
    test: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/post');
    const mapped = req.prepareArgs({ test: [test, string()] });
    req.query('test', mapped.test);
    return req.call(requestOptions);
  }
}
